# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-01 06:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.date(2017, 9, 1)),
        ),
        migrations.AddField(
            model_name='todo',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='finished_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 9, 1, 9, 24, 7, 681286)),
        ),
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 9, 1, 9, 24, 7, 681264)),
        ),
    ]
